1.Added test file in tests/topology that tests all three cases of cell division
2.Made the additions in the main cell_division function

3. I tested the edits myself inorder for this process to make sense

4. I want to contribute more in the future but I had trouble using the fork I created on my local comjputer. I was able to test because i didnt need cgal. However, if i needed cgal I wouldnt be able to test the code.

**Trouble installing cgal in my mac**

 * Here are steps i took to use a custom tyssue installation *

I pulled the tyssue branch i created in github on my computer

Created a fresh conda environment

used | conda install --only-deps -c conda-forge tyssue | to install only dependencies

then I run | python setup.py install |

Then when I tried to use hex_grid in a script in my local computer got an error (other imports where fine) :

Traceback (most recent call last):
  File "pbc_guillaume_share.py", line 19, in <module>
    from tyssue.generation import hexa_grid2d
  File "/anaconda3/envs/tyssue_dev/lib/python3.7/site-packages/tyssue-0.6.4-py3.7-macosx-10.9-x86_64.egg/tyssue/generation/__init__.py", line 8, in <module>
    from .shapes import *
  File "/anaconda3/envs/tyssue_dev/lib/python3.7/site-packages/tyssue-0.6.4-py3.7-macosx-10.9-x86_64.egg/tyssue/generation/shapes.py", line 22, in <module>
    from .cpp import mesh_generation
ImportError: cannot import name 'mesh_generation' from 'tyssue.generation.cpp' (/anaconda3/envs/tyssue_dev/lib/python3.7/site-packages/tyssue-0.6.4-py3.7-macosx-10.9-x86_64.egg/tyssue/generation/cpp/__init__.py)